language: rust
rust:
  - stable
  - beta
  - nightly
addons:
  apt:
    sources:
    - sourceline: 'ppa:mosquitto-dev/mosquitto-ppa'
    packages:
    - mosquitto
before_install:
  - "cd tests/test-ca ; mosquitto -c mosquitto.conf &"
script:
  - cargo build --verbose --all
  - cargo test --verbose --all
matrix:
  allow_failures:
    - rust: nightly
