language: rust
rust:
  - stable
  - beta
  - nightly
addons:
  apt:
    sources:
    - sourceline: 'ppa:mosquitto-dev/mosquitto-ppa'
    packages:
    - mosquitto
script:
   - cargo build --verbose --all
   - ./.travis.sh
matrix:
   allow_failures:
     - rust: nightly
