[package]
authors = ["kteza1 <k.teza1@gmail.com>"]
name = "rumqtt"
version = "0.10.0"
description = "A fast, lockfree mqtt client"
documentation = "http://ather-energy.github.io/RuMqtt/rumqtt/index.html"
repository = "https://github.com/Ather-Energy/RuMqtt"
readme = "README.md"
license = "Unlicense/MIT"
exclude = ["tests/test-utils"]
keywords = ["mqtt", "iot"]

[dependencies]
log = "0.3"
rand = "0.3"
time = "0.1"
threadpool = "1.3"
quick-error = "1.1"
mqtt-protocol = { git = "https://github.com/creativcoder/mqtt-rs", branch="serde_derive" }
persist = { git = "https://github.com/creativcoder/persist", branch="purge_backup" }
clippy = {version = "*", optional = true}
openssl = { version = "0.9" }
serde = "0.9"
serde_derive = "0.9"

[dev-dependencies]
env_logger = "0.3"
